sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
script:
  - yarn start validate
after_success:
  - yarn global add codecov semantic-release
  - codecov
  - yarn start release
  - yarn start validate.examples
  - semantic-release pre && npm publish && semantic-release post
branches:
  only:
    - master
